### ISSUE TITLE
when using color_point_2_depth_point, sometime an error will occur

### ISSUE THREAD

**Issue by jdyjjj** [KonstantinosAng/PyKinect2-Mapper-Functions#10]
as you can see in this picture, this is my code.
![image](https://user-images.githubusercontent.com/73057174/170714926-56d95356-5cf4-4e17-9a18-66d245319475.png)
and there will always be an error:
```
Traceback (most recent call last):
  File "video_kinect.py", line 462, in <module>
    x,y = color_point_2_depth_point(a._kinect,_DepthSpacePoint,a._kinect._depth_frame_data,[int(center_x),int(center_y)])
  File "video_kinect.py", line 365, in color_point_2_depth_point
    return [int(depth_x), int(depth_y)]
OverflowError: cannot convert float infinity to integer
```
I really can not understand why  this error occurs. Thank you!

**Comment by KonstantinosAng** [comment]
Hello, the problem is with int(center_x), int(center_y). you cannot be sure that the Kinect values will always be numeric (float or int). The kinect is susceptible to external noise, such as light and reflections, and its values can overflow and return as '-inf'.

Thus, the error: cannot convert float infinity to int

i suggest you do int(center_x) if center_x != float('-inf') and center_x != float('inf') else center_x, and the same for center_y

**Comment by jdyjjj** [comment]
![image](https://user-images.githubusercontent.com/73057174/170717885-bbfc9f47-96ac-4815-b62c-511b50842c7f.png)

**Comment by jdyjjj** [comment]
Thank you for your answering. But the reason for this error is depth_x and depth_y is inf. And center_x and center_y is int.

**Comment by KonstantinosAng** [comment]
Then you have to handle their value:

Also numpy can filter these values faster with:

color2depth_points = color2depth_points[np.all(color2depth_points != float('-inf'), axis=1)]  # remove -inf

and then do:

depth_x = color2depth_points[color_point[1] * 1920 + color_point[0] - 1].x
depth_y = color2depth_points[color_point[1] * 1920 + color_point[0] - 1].y

**Comment by jdyjjj** [comment]
Thank you for your answer. I try your method to remove inf, but this method will make a new error that in this picture:
![image](https://user-images.githubusercontent.com/73057174/170721421-27d5f3b9-bd2b-49c6-8c6b-988a8b54276c.png)

**Comment by KonstantinosAng** [comment]
try removing the option axis=1

color2depth_points = color2depth_points[np.all(color2depth_points != float('-inf'))] # remove -inf

**Comment by jdyjjj** [comment]
This is bug now, but I really don't know why this error occurs.

![image](https://user-images.githubusercontent.com/73057174/170722830-3ee519c6-5dad-476b-9dc0-2c4dc481cf9b.png)

![image](https://user-images.githubusercontent.com/73057174/170723075-935af257-2ced-468d-b690-0088b22c17b3.png)

**Comment by KonstantinosAng** [comment]
ok, I think it is better for me to change it in the library than this. I will push the changes in short in this repo

**Comment by KonstantinosAng** [comment]
run git pull and try again without the:

color2depth_points = color2depth_points[np.all(color2depth_points != float('-inf'))] # remove -inf
